### ISSUE TITLE
Test fails with bsdtar

### ISSUE THREAD

**Issue by idealseal** [pkgcraft/pkgcraft#233]
The pkgcraft shell::commands::unpack::tests::archives test fails with bsdtar. ~libarchive's tar lacks the -I .~

#### Test output

```
tar: -I: Cannot stat: No such file or directory
tar: gzip: Cannot stat: No such file or directory
tar: -f: Cannot stat: No such file or directory
tar: /tmp/.tmpKTlO8I/distdir/a.tar.gz: Cannot stat: No such file or directory
tar: Error exit delayed from previous errors.
thread 'shell::commands::unpack::tests::archives' panicked at crates/pkgcraft/src/shell/commands/unpack.rs:229:62:
called `Result::unwrap()` on an `Err` value: IO("failed running: \"tar\" \"-c\" \"dir\" \"-I\" \"gzip\" \"-f\" \"/tmp/.tmpKTlO8I/distdir/a.tar.gz\"")
```

**Comment by radhermit** [comment]
Not high on my priority list, but if you want to give it a shot making the tar archive type support both would probably be acceptable.

**Comment by radhermit** [comment]
After glancing at the spec, it does state that GNU tar is expected for unpacking tarballs (and that ebuilds should ensure it exists) so it's probably easiest just to swap out `tar` references with `gtar` assuming most non-Gentoo distros package it the same way so that file exists if GNU tar is installed on a system.

**Comment by idealseal** [comment]
`--use-compress-program` works in my shell, but the test still fail when substituting the `-I` flag with it.

Switching to `gtar` works.

**Comment by radhermit** [comment]
The issue is that not all distros even have it installed as gtar (and pkgcraft isn't targeting to run or test only on Gentoo-like systems), presumably because they don't provide libarchive's tar alternative. So if pkgcraft continues to use an external tar binary it will probably have to try gtar first and then fall back to tar.

Alternatively, it's probably possible to use the tar crate instead which shouldn't have too terrible of performance as long as a bufreader is used along with a separate thread for decompressing as necessary.

**Comment by idealseal** [comment]
> --use-compress-program works in my shell, but the test still fail when substituting the -I flag with it.

So the issue is that the `-c` flag must be last or other option will be interpreted as files.
