### ISSUE TITLE
Ebuild parser

### ISSUE THREAD

**Issue by lu-zero** [pkgcraft/pkgcraft#3]
In order to correctly parse an ebuild nearly a full [bash](https://www.gnu.org/software/bash/manual/bash.html) parser is required.

- [bash](https://www.gnu.org/software/bash/manual/bash.html) itself could be used as a pre-processor
- [conch-parser](https://github.com/ipetkov/conch-parser) is a pure rust `sh` parser that could be expanded
- [bash-parser](https://github.com/vorpaljs/bash-parser) is a pure `js` implementation, its grammar is in [jison](https://github.com/zaach/jison) so it could be easy to look at it in case we want to spin a complete side project
- [mvdan/sh](https://github.com/mvdan/sh) is a pure `go` implementation it sports a `shfmt` tool that can produce a json AST that might be easy to consume.

**Comment by radhermit** [comment]
Closing this since I've chosen to wrap bash into the [scallop crate](https://github.com/pkgcraft/scallop)  (probably not the final name) and hook into bash's C internals via that. Rewriting an entire bash parser and enough support for various things like parameter substitution required for ebuild parsing doesn't sound like a great use of time.

Personally speaking, if I was to consider that I'd rather consider replacing bash entirely with some extensible DSL that would be much more modern and development friendly compared to bash.
